server.port=${PORT:8080}

# Cloud SQL via Unix socket (correct format)
spring.datasource.url=jdbc:postgresql:///employeedb?cloudSqlInstance=createorder-490108:asia-south1:emp-db-new&socketFactory=com.google.cloud.sql.postgres.SocketFactory

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Prevent crash if DB is slow on cold start
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.sql.init.mode=never